# Generated by Django 4.2.7 on 2023-11-26 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vender_management_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_model',
            name='vendor_code',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Purchase_order_Model',
            fields=[
                ('po_number', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('order_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField()),
                ('items', models.JSONField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('quality_rating', models.FloatField()),
                ('issue_date', models.DateTimeField()),
                ('acknowledgment_date', models.DateTimeField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vender_management_system.vendor_model')),
            ],
        ),
        migrations.CreateModel(
            name='Historical_Performance_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('on_time_delivery_rate', models.FloatField()),
                ('quality_rating_avg', models.FloatField()),
                ('average_response_time', models.FloatField()),
                ('fulfillment_rate', models.FloatField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vender_management_system.vendor_model')),
            ],
        ),
    ]
