# Generated by Django 4.2.7 on 2023-11-26 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vender_management_system', '0002_alter_vendor_model_vendor_code_purchase_order_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historical_performance_model',
            name='id',
        ),
        migrations.AlterField(
            model_name='historical_performance_model',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vender_management_system.vendor_model'),
        ),
    ]
