# Generated by Django 4.2.7 on 2023-11-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vender_management_system', '0005_alter_vendor_model_vendor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_model',
            name='po_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
