# Generated by Django 4.2.7 on 2023-11-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vender_management_system', '0006_alter_purchase_order_model_po_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_model',
            name='quality_rating',
            field=models.FloatField(default=0, null=True),
        ),
    ]
