# Generated by Django 4.2.7 on 2023-11-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vender_management_system', '0007_alter_purchase_order_model_quality_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_model',
            name='quality_rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
