# Generated by Django 4.2.7 on 2023-12-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vender_management_system', '0008_alter_purchase_order_model_quality_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical_performance_model',
            name='average_response_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vendor_model',
            name='average_response_time',
            field=models.DateTimeField(),
        ),
    ]
